version: '3'
services:
  postgres:
    image: postgres:14.3
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: keycloak
    ports:
      - "5432:5432"
  keycloak:
    command:
      - start-dev --db=postgres
    restart: always
    build: .
    image: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME_STRICT: 'false'
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: mysecretpassword
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
#      KC_HTTP_ENABLED: 'true'
      KC_HTTP_RELATIVE_PATH: /auth
      KC_PROXY: 'edge'
    ports:
      - "8080:8080"
      - "8443:8443"